//! FreeBSD AHCI PCI device IDs and controller quirks.
//!
//! Translated from FreeBSD `sys/dev/ahci/ahci_pci.c` at
//! `c2b7fe4a9e94a0edba9dd2772874928b565c4f9e` (BSD-2-Clause).
//! Copyright (c) 2009-2012 Alexander Motin <mav@FreeBSD.org>

use axdriver_block::ahci::regs::*;

/// One vendor/device/revision match and its AHCI hardware quirks.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PciIdQuirk {
    /// Upstream packed PCI ID: device in bits 31:16, vendor in 15:0.
    pub id: u32,
    /// First hardware revision to which this row applies.
    pub revision: u8,
    /// Human-readable upstream device name.
    pub name: &'static str,
    /// `AHCI_Q_*` quirk flags from `ahci.h`.
    pub quirks: u32,
}

// upstream: ahci_pci.c ahci_ids[]
pub const AHCI_PCI_IDS: &[PciIdQuirk] = &[
    PciIdQuirk {
        id: 0x43801002,
        revision: 0,
        name: "AMD SB600",
        quirks: AHCI_Q_NOMSI | AHCI_Q_ATI_PMP_BUG | AHCI_Q_MAXIO_64K,
    },
    PciIdQuirk {
        id: 0x43901002,
        revision: 0,
        name: "AMD SB7x0/SB8x0/SB9x0",
        quirks: AHCI_Q_ATI_PMP_BUG | AHCI_Q_1MSI,
    },
    PciIdQuirk {
        id: 0x43911002,
        revision: 0,
        name: "AMD SB7x0/SB8x0/SB9x0",
        quirks: AHCI_Q_ATI_PMP_BUG | AHCI_Q_1MSI,
    },
    PciIdQuirk {
        id: 0x43921002,
        revision: 0,
        name: "AMD SB7x0/SB8x0/SB9x0",
        quirks: AHCI_Q_ATI_PMP_BUG | AHCI_Q_1MSI,
    },
    PciIdQuirk {
        id: 0x43931002,
        revision: 0,
        name: "AMD SB7x0/SB8x0/SB9x0",
        quirks: AHCI_Q_ATI_PMP_BUG | AHCI_Q_1MSI,
    },
    PciIdQuirk {
        id: 0x43941002,
        revision: 0,
        name: "AMD SB7x0/SB8x0/SB9x0",
        quirks: AHCI_Q_ATI_PMP_BUG | AHCI_Q_1MSI,
    },
    PciIdQuirk {
        id: 0x43951002,
        revision: 0,
        name: "AMD SB8x0/SB9x0",
        quirks: AHCI_Q_ATI_PMP_BUG,
    },
    PciIdQuirk {
        id: 0x43b61022,
        revision: 0,
        name: "AMD X399",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x43b51022,
        revision: 0,
        name: "AMD 300 Series",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x43b71022,
        revision: 0,
        name: "AMD 300 Series",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x43c81022,
        revision: 0,
        name: "AMD 400 Series",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x43eb1022,
        revision: 0,
        name: "AMD 500 Series",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x43f61022,
        revision: 0,
        name: "AMD 600 Series",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x78001022,
        revision: 0,
        name: "AMD Hudson-2",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x78011022,
        revision: 0,
        name: "AMD Hudson-2",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x78021022,
        revision: 0,
        name: "AMD Hudson-2",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x78031022,
        revision: 0,
        name: "AMD Hudson-2",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x78041022,
        revision: 0,
        name: "AMD Hudson-2",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x79001022,
        revision: 0,
        name: "AMD KERNCZ",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x79011022,
        revision: 0,
        name: "AMD KERNCZ",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x79021022,
        revision: 0,
        name: "AMD KERNCZ",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x79031022,
        revision: 0,
        name: "AMD KERNCZ",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x79041022,
        revision: 0,
        name: "AMD KERNCZ",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x79161022,
        revision: 0,
        name: "AMD KERNCZ (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06011b21,
        revision: 0,
        name: "ASMedia ASM1060",
        quirks: AHCI_Q_NOCCS | AHCI_Q_NOAUX,
    },
    PciIdQuirk {
        id: 0x06021b21,
        revision: 0,
        name: "ASMedia ASM1060",
        quirks: AHCI_Q_NOCCS | AHCI_Q_NOAUX,
    },
    PciIdQuirk {
        id: 0x06111b21,
        revision: 0,
        name: "ASMedia ASM1061",
        quirks: AHCI_Q_NOCCS | AHCI_Q_NOAUX,
    },
    PciIdQuirk {
        id: 0x06121b21,
        revision: 0,
        name: "ASMedia ASM1062",
        quirks: AHCI_Q_NOCCS | AHCI_Q_NOAUX,
    },
    PciIdQuirk {
        id: 0x06201b21,
        revision: 0,
        name: "ASMedia ASM106x",
        quirks: AHCI_Q_NOCCS | AHCI_Q_NOAUX,
    },
    PciIdQuirk {
        id: 0x06211b21,
        revision: 0,
        name: "ASMedia ASM106x",
        quirks: AHCI_Q_NOCCS | AHCI_Q_NOAUX,
    },
    PciIdQuirk {
        id: 0x06221b21,
        revision: 0,
        name: "ASMedia ASM106x",
        quirks: AHCI_Q_NOCCS | AHCI_Q_NOAUX,
    },
    PciIdQuirk {
        id: 0x06241b21,
        revision: 0,
        name: "ASMedia ASM106x",
        quirks: AHCI_Q_NOCCS | AHCI_Q_NOAUX,
    },
    PciIdQuirk {
        id: 0x06251b21,
        revision: 0,
        name: "ASMedia ASM106x",
        quirks: AHCI_Q_NOCCS | AHCI_Q_NOAUX,
    },
    PciIdQuirk {
        id: 0x10621b21,
        revision: 0,
        name: "ASMedia ASM116x",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x10641b21,
        revision: 0,
        name: "ASMedia ASM116x",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x11641b21,
        revision: 0,
        name: "ASMedia ASM116x",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x11651b21,
        revision: 0,
        name: "ASMedia ASM116x",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x11661b21,
        revision: 0,
        name: "ASMedia ASM116x",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x79011d94,
        revision: 0,
        name: "Hygon KERNCZ",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x0f228086,
        revision: 0,
        name: "Intel BayTrail",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x0f238086,
        revision: 0,
        name: "Intel BayTrail",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x26528086,
        revision: 0,
        name: "Intel ICH6",
        quirks: AHCI_Q_NOFORCE,
    },
    PciIdQuirk {
        id: 0x26538086,
        revision: 0,
        name: "Intel ICH6M",
        quirks: AHCI_Q_NOFORCE,
    },
    PciIdQuirk {
        id: 0x26818086,
        revision: 0,
        name: "Intel ESB2",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x26828086,
        revision: 0,
        name: "Intel ESB2",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x26838086,
        revision: 0,
        name: "Intel ESB2",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x27c18086,
        revision: 0,
        name: "Intel ICH7",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x27c38086,
        revision: 0,
        name: "Intel ICH7",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x27c58086,
        revision: 0,
        name: "Intel ICH7M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x27c68086,
        revision: 0,
        name: "Intel ICH7M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x28218086,
        revision: 0,
        name: "Intel ICH8",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x28228086,
        revision: 0,
        name: "Intel ICH8+ (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x28248086,
        revision: 0,
        name: "Intel ICH8",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x28298086,
        revision: 0,
        name: "Intel ICH8M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x282a8086,
        revision: 0,
        name: "Intel ICH8M+ (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x29228086,
        revision: 0,
        name: "Intel ICH9",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x29238086,
        revision: 0,
        name: "Intel ICH9",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x29248086,
        revision: 0,
        name: "Intel ICH9",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x29258086,
        revision: 0,
        name: "Intel ICH9",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x29278086,
        revision: 0,
        name: "Intel ICH9",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x29298086,
        revision: 0,
        name: "Intel ICH9M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x292a8086,
        revision: 0,
        name: "Intel ICH9M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x292b8086,
        revision: 0,
        name: "Intel ICH9M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x292c8086,
        revision: 0,
        name: "Intel ICH9M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x292f8086,
        revision: 0,
        name: "Intel ICH9M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x294d8086,
        revision: 0,
        name: "Intel ICH9",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x294e8086,
        revision: 0,
        name: "Intel ICH9M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x3a028086,
        revision: 0,
        name: "Intel ICH10",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x3a058086,
        revision: 0,
        name: "Intel ICH10 (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x3a228086,
        revision: 0,
        name: "Intel ICH10",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x3a258086,
        revision: 0,
        name: "Intel ICH10 (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x3b228086,
        revision: 0,
        name: "Intel Ibex Peak",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x3b238086,
        revision: 0,
        name: "Intel Ibex Peak",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x3b258086,
        revision: 0,
        name: "Intel Ibex Peak (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x3b298086,
        revision: 0,
        name: "Intel Ibex Peak-M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x3b2c8086,
        revision: 0,
        name: "Intel Ibex Peak-M (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x3b2f8086,
        revision: 0,
        name: "Intel Ibex Peak-M",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06d68086,
        revision: 0,
        name: "Intel Comet Lake (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19b08086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19b18086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19b28086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19b38086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19b48086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19b58086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19b68086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19b78086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19be8086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19bf8086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19c08086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19c18086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19c28086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19c38086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19c48086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19c58086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19c68086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19c78086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19ce8086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x19cf8086,
        revision: 0,
        name: "Intel Denverton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1c028086,
        revision: 0,
        name: "Intel Cougar Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1c038086,
        revision: 0,
        name: "Intel Cougar Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1c048086,
        revision: 0,
        name: "Intel Cougar Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1c058086,
        revision: 0,
        name: "Intel Cougar Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1c068086,
        revision: 0,
        name: "Intel Cougar Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1d028086,
        revision: 0,
        name: "Intel Patsburg",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1d048086,
        revision: 0,
        name: "Intel Patsburg",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1d068086,
        revision: 0,
        name: "Intel Patsburg",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x28268086,
        revision: 0,
        name: "Intel Patsburg+ (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1e028086,
        revision: 0,
        name: "Intel Panther Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1e038086,
        revision: 0,
        name: "Intel Panther Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1e048086,
        revision: 0,
        name: "Intel Panther Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1e058086,
        revision: 0,
        name: "Intel Panther Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1e068086,
        revision: 0,
        name: "Intel Panther Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1e078086,
        revision: 0,
        name: "Intel Panther Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1e0e8086,
        revision: 0,
        name: "Intel Panther Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1e0f8086,
        revision: 0,
        name: "Intel Panther Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f228086,
        revision: 0,
        name: "Intel Avoton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f238086,
        revision: 0,
        name: "Intel Avoton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f248086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f258086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f268086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f278086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f2e8086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f2f8086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f328086,
        revision: 0,
        name: "Intel Avoton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f338086,
        revision: 0,
        name: "Intel Avoton",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f348086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f358086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f368086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f378086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f3e8086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x1f3f8086,
        revision: 0,
        name: "Intel Avoton (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x23a38086,
        revision: 0,
        name: "Intel Coleto Creek",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x31e38086,
        revision: 0,
        name: "Intel Gemini Lake",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x4b638086,
        revision: 0,
        name: "Intel Elkhart Lake",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x5ae38086,
        revision: 0,
        name: "Intel Apollo Lake",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x7ae28086,
        revision: 0,
        name: "Intel Alder Lake",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c028086,
        revision: 0,
        name: "Intel Lynx Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c038086,
        revision: 0,
        name: "Intel Lynx Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c048086,
        revision: 0,
        name: "Intel Lynx Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c058086,
        revision: 0,
        name: "Intel Lynx Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c068086,
        revision: 0,
        name: "Intel Lynx Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c078086,
        revision: 0,
        name: "Intel Lynx Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c0e8086,
        revision: 0,
        name: "Intel Lynx Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c0f8086,
        revision: 0,
        name: "Intel Lynx Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c828086,
        revision: 0,
        name: "Intel Wildcat Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c838086,
        revision: 0,
        name: "Intel Wildcat Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c848086,
        revision: 0,
        name: "Intel Wildcat Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c858086,
        revision: 0,
        name: "Intel Wildcat Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c868086,
        revision: 0,
        name: "Intel Wildcat Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c878086,
        revision: 0,
        name: "Intel Wildcat Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c8e8086,
        revision: 0,
        name: "Intel Wildcat Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8c8f8086,
        revision: 0,
        name: "Intel Wildcat Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8d028086,
        revision: 0,
        name: "Intel Wellsburg",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8d048086,
        revision: 0,
        name: "Intel Wellsburg (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8d068086,
        revision: 0,
        name: "Intel Wellsburg (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8d628086,
        revision: 0,
        name: "Intel Wellsburg",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8d648086,
        revision: 0,
        name: "Intel Wellsburg (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8d668086,
        revision: 0,
        name: "Intel Wellsburg (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x8d6e8086,
        revision: 0,
        name: "Intel Wellsburg (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x28238086,
        revision: 0,
        name: "Intel Wellsburg+ (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x28278086,
        revision: 0,
        name: "Intel Wellsburg+ (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c028086,
        revision: 0,
        name: "Intel Lynx Point-LP",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c038086,
        revision: 0,
        name: "Intel Lynx Point-LP",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c048086,
        revision: 0,
        name: "Intel Lynx Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c058086,
        revision: 0,
        name: "Intel Lynx Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c068086,
        revision: 0,
        name: "Intel Lynx Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c078086,
        revision: 0,
        name: "Intel Lynx Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c0e8086,
        revision: 0,
        name: "Intel Lynx Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c0f8086,
        revision: 0,
        name: "Intel Lynx Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c838086,
        revision: 0,
        name: "Intel Wildcat Point-LP",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c858086,
        revision: 0,
        name: "Intel Wildcat Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c878086,
        revision: 0,
        name: "Intel Wildcat Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9c8f8086,
        revision: 0,
        name: "Intel Wildcat Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9d038086,
        revision: 0,
        name: "Intel Sunrise Point-LP",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9d058086,
        revision: 0,
        name: "Intel Sunrise Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x9d078086,
        revision: 0,
        name: "Intel Sunrise Point-LP (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa1028086,
        revision: 0,
        name: "Intel Sunrise Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa1038086,
        revision: 0,
        name: "Intel Sunrise Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa1058086,
        revision: 0,
        name: "Intel Sunrise Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa1068086,
        revision: 0,
        name: "Intel Sunrise Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa1078086,
        revision: 0,
        name: "Intel Sunrise Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa10f8086,
        revision: 0,
        name: "Intel Sunrise Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa1828086,
        revision: 0,
        name: "Intel Lewisburg",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa1868086,
        revision: 0,
        name: "Intel Lewisburg (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa1d28086,
        revision: 0,
        name: "Intel Lewisburg",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa1d68086,
        revision: 0,
        name: "Intel Lewisburg (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa2028086,
        revision: 0,
        name: "Intel Lewisburg",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa2068086,
        revision: 0,
        name: "Intel Lewisburg (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa2528086,
        revision: 0,
        name: "Intel Lewisburg",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa2568086,
        revision: 0,
        name: "Intel Lewisburg (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa2828086,
        revision: 0,
        name: "Intel Union Point",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa2868086,
        revision: 0,
        name: "Intel Union Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa28e8086,
        revision: 0,
        name: "Intel Union Point (RAID)",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa3528086,
        revision: 0,
        name: "Intel Cannon Lake",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa3538086,
        revision: 0,
        name: "Intel Cannon Lake",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x23238086,
        revision: 0,
        name: "Intel DH89xxCC",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x2360197b,
        revision: 0,
        name: "JMicron JMB360",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x2361197b,
        revision: 0,
        name: "JMicron JMB361",
        quirks: AHCI_Q_NOFORCE | AHCI_Q_1CH,
    },
    PciIdQuirk {
        id: 0x2362197b,
        revision: 0,
        name: "JMicron JMB362",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x2363197b,
        revision: 0,
        name: "JMicron JMB363",
        quirks: AHCI_Q_NOFORCE,
    },
    PciIdQuirk {
        id: 0x2365197b,
        revision: 0,
        name: "JMicron JMB365",
        quirks: AHCI_Q_NOFORCE,
    },
    PciIdQuirk {
        id: 0x2366197b,
        revision: 0,
        name: "JMicron JMB366",
        quirks: AHCI_Q_NOFORCE,
    },
    PciIdQuirk {
        id: 0x2368197b,
        revision: 0,
        name: "JMicron JMB368",
        quirks: AHCI_Q_NOFORCE,
    },
    PciIdQuirk {
        id: 0x2392197b,
        revision: 0,
        name: "JMicron JMB388",
        quirks: AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x0585197b,
        revision: 0,
        name: "JMicron JMB58x",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x01221c28,
        revision: 0,
        name: "Lite-On Plextor M6E (Marvell 88SS9183)",
        quirks: AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x611111ab,
        revision: 0,
        name: "Marvell 88SE6111",
        quirks: AHCI_Q_NOFORCE | AHCI_Q_NOPMP | AHCI_Q_1CH | AHCI_Q_EDGEIS,
    },
    PciIdQuirk {
        id: 0x612111ab,
        revision: 0,
        name: "Marvell 88SE6121",
        quirks: AHCI_Q_NOFORCE
            | AHCI_Q_NOPMP
            | AHCI_Q_2CH
            | AHCI_Q_EDGEIS
            | AHCI_Q_NONCQ
            | AHCI_Q_NOCOUNT,
    },
    PciIdQuirk {
        id: 0x614111ab,
        revision: 0,
        name: "Marvell 88SE6141",
        quirks: AHCI_Q_NOFORCE
            | AHCI_Q_NOPMP
            | AHCI_Q_4CH
            | AHCI_Q_EDGEIS
            | AHCI_Q_NONCQ
            | AHCI_Q_NOCOUNT,
    },
    PciIdQuirk {
        id: 0x614511ab,
        revision: 0,
        name: "Marvell 88SE6145",
        quirks: AHCI_Q_NOFORCE
            | AHCI_Q_NOPMP
            | AHCI_Q_4CH
            | AHCI_Q_EDGEIS
            | AHCI_Q_NONCQ
            | AHCI_Q_NOCOUNT,
    },
    PciIdQuirk {
        id: 0x91201b4b,
        revision: 0,
        name: "Marvell 88SE912x",
        quirks: AHCI_Q_EDGEIS | AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x91231b4b,
        revision: 17,
        name: "Marvell 88SE912x",
        quirks: AHCI_Q_ALTSIG | AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x91231b4b,
        revision: 0,
        name: "Marvell 88SE912x",
        quirks: AHCI_Q_EDGEIS | AHCI_Q_SATA2 | AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x91251b4b,
        revision: 0,
        name: "Marvell 88SE9125",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x91281b4b,
        revision: 0,
        name: "Marvell 88SE9128",
        quirks: AHCI_Q_ALTSIG | AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x91301b4b,
        revision: 0,
        name: "Marvell 88SE9130",
        quirks: AHCI_Q_ALTSIG | AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x91701b4b,
        revision: 0,
        name: "Marvell 88SE9170",
        quirks: AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x91721b4b,
        revision: 0,
        name: "Marvell 88SE9172",
        quirks: AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x917a1b4b,
        revision: 0,
        name: "Marvell 88SE917A",
        quirks: AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x91821b4b,
        revision: 0,
        name: "Marvell 88SE9182",
        quirks: AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x91831b4b,
        revision: 0,
        name: "Marvell 88SS9183",
        quirks: AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x91a01b4b,
        revision: 0,
        name: "Marvell 88SE91Ax",
        quirks: AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x91a31b4b,
        revision: 0,
        name: "Marvell 88SE9128",
        quirks: AHCI_Q_ALTSIG | AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x92151b4b,
        revision: 0,
        name: "Marvell 88SE9215",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x92201b4b,
        revision: 0,
        name: "Marvell 88SE9220",
        quirks: AHCI_Q_ALTSIG | AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x92301b4b,
        revision: 0,
        name: "Marvell 88SE9230",
        quirks: AHCI_Q_ALTSIG | AHCI_Q_IOMMU_BUSWIDE | AHCI_Q_SLOWDEV,
    },
    PciIdQuirk {
        id: 0x92351b4b,
        revision: 0,
        name: "Marvell 88SE9235",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06201103,
        revision: 0,
        name: "HighPoint RocketRAID 620",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06201b4b,
        revision: 0,
        name: "HighPoint RocketRAID 620",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06221103,
        revision: 0,
        name: "HighPoint RocketRAID 622",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06221b4b,
        revision: 0,
        name: "HighPoint RocketRAID 622",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06401103,
        revision: 0,
        name: "HighPoint RocketRAID 640",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06401b4b,
        revision: 0,
        name: "HighPoint RocketRAID 640",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06441103,
        revision: 0,
        name: "HighPoint RocketRAID 644",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06441b4b,
        revision: 0,
        name: "HighPoint RocketRAID 644",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06411103,
        revision: 0,
        name: "HighPoint RocketRAID 640L",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x06421103,
        revision: 0,
        name: "HighPoint RocketRAID 642L",
        quirks: AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x06451103,
        revision: 0,
        name: "HighPoint RocketRAID 644L",
        quirks: AHCI_Q_IOMMU_BUSWIDE,
    },
    PciIdQuirk {
        id: 0x044c10de,
        revision: 0,
        name: "NVIDIA MCP65",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x044d10de,
        revision: 0,
        name: "NVIDIA MCP65",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x044e10de,
        revision: 0,
        name: "NVIDIA MCP65",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x044f10de,
        revision: 0,
        name: "NVIDIA MCP65",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x045c10de,
        revision: 0,
        name: "NVIDIA MCP65",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x045d10de,
        revision: 0,
        name: "NVIDIA MCP65",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x045e10de,
        revision: 0,
        name: "NVIDIA MCP65",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x045f10de,
        revision: 0,
        name: "NVIDIA MCP65",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055010de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055110de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055210de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055310de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055410de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055510de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055610de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055710de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055810de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055910de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055a10de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x055b10de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x058410de,
        revision: 0,
        name: "NVIDIA MCP67",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07f010de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07f110de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07f210de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07f310de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07f410de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07f510de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07f610de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07f710de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07f810de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07f910de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07fa10de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x07fb10de,
        revision: 0,
        name: "NVIDIA MCP73",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ad010de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ad110de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ad210de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ad310de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ad410de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ad510de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ad610de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ad710de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ad810de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ad910de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ada10de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0adb10de,
        revision: 0,
        name: "NVIDIA MCP77",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ab410de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ab510de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ab610de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ab710de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ab810de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0ab910de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0aba10de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0abb10de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0abc10de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0abd10de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0abe10de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0abf10de,
        revision: 0,
        name: "NVIDIA MCP79",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8410de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8510de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOFORCE | AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8610de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8710de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8810de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8910de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8a10de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8b10de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8c10de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8d10de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8e10de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x0d8f10de,
        revision: 0,
        name: "NVIDIA MCP89",
        quirks: AHCI_Q_NOAA,
    },
    PciIdQuirk {
        id: 0x3781105a,
        revision: 0,
        name: "Promise TX8660",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x33491106,
        revision: 0,
        name: "VIA VT8251",
        quirks: AHCI_Q_NOPMP | AHCI_Q_NONCQ,
    },
    PciIdQuirk {
        id: 0x62871106,
        revision: 0,
        name: "VIA VT8251",
        quirks: AHCI_Q_NOPMP | AHCI_Q_NONCQ,
    },
    PciIdQuirk {
        id: 0x11841039,
        revision: 0,
        name: "SiS 966",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x11851039,
        revision: 0,
        name: "SiS 968",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0x01861039,
        revision: 0,
        name: "SiS 968",
        quirks: 0,
    },
    PciIdQuirk {
        id: 0xa01c177d,
        revision: 0,
        name: "ThunderX",
        quirks: AHCI_Q_ABAR0 | AHCI_Q_1MSI,
    },
    PciIdQuirk {
        id: 0x00311c36,
        revision: 0,
        name: "Annapurna",
        quirks: AHCI_Q_FORCE_PI | AHCI_Q_RESTORE_CAP | AHCI_Q_NOMSIX,
    },
    PciIdQuirk {
        id: 0x1600144d,
        revision: 0,
        name: "Samsung",
        quirks: AHCI_Q_NOMSI,
    },
    PciIdQuirk {
        id: 0x07e015ad,
        revision: 0,
        name: "VMware",
        quirks: 0,
    },
];

/// Scan all upstream rows for an ID and retain the most specific applicable
/// revision (the table may contain multiple revision-qualified rows).
pub fn identify(vendor_id: u16, device_id: u16, revision: u8) -> Option<PciIdQuirk> {
    let id = (u32::from(device_id) << 16) | u32::from(vendor_id);
    AHCI_PCI_IDS
        .iter()
        .copied()
        .filter(|entry| entry.id == id && entry.revision <= revision)
        .max_by_key(|entry| entry.revision)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_ids_retain_upstream_quirks_and_names() {
        let sb600 = identify(0x1002, 0x4380, 0).unwrap();
        assert_eq!(sb600.name, "AMD SB600");
        assert_eq!(
            sb600.quirks,
            AHCI_Q_NOMSI | AHCI_Q_ATI_PMP_BUG | AHCI_Q_MAXIO_64K
        );
        let ich9 = identify(0x8086, 0x2922, 0).unwrap();
        assert_eq!(ich9.name, "Intel ICH9");
        assert_eq!(ich9.quirks, 0);
    }

    #[test]
    fn unknown_ids_do_not_inherit_an_unrelated_quirk() {
        assert_eq!(identify(0xffff, 0xffff, 0), None);
    }
}
