[package]
name = "thekernel-axdriver-net"
version = "0.1.4-preview.3"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>", "ChengXiang Qi <kuangjux@outlook.com>", "朝倉水希 <asakuramizu111@gmail.com>", "Yu Chen <yuchen@tsinghua.edu.cn>"]
description = "Common traits and types for network device drivers"
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/axdriver_crates"

[features]
default = []
fxmac = ["dep:fxmac_rs"]
ixgbe = ["dep:ixgbe-driver"]

[lib]
name = "axdriver_net"
path = "src/lib.rs"

[dependencies]
axdriver_base = { package = "thekernel-axdriver-base", path = "../thekernel-axdriver-base", version = "0.1.4-preview.3" }
fxmac_rs = { version = "0.2", optional = true }
ixgbe-driver = { version = "0.1.1-preview.1", optional = true }
log = "0.4"
spin = "0.9"

[package.metadata.thekernel]
layer = "platform"
