[package]
repository.workspace = true
publish.workspace = true
rust-version.workspace = true
name = "tk-axdriver-input"
version = "0.1.0"
edition = "2021"
description = "Common traits and types for input device drivers"
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"

[dependencies]
axdriver_base = { package = "tk-axdriver-base", path = "../tk-axdriver-base", version = "0.1.0" }
strum = { version = "0.27.2", default-features = false, features = ["derive"] }

[package.metadata.thekernel]
layer = "platform"
