//! Every register the modeset sequence owns, as one table.
//!
//! This file is generated from the submodules beside it by the script recorded
//! in the commit that added it; the alternative was five hand-maintained
//! `&[Register]` literals that a reader would have to diff against the
//! declarations.  The tables exist so the properties the access machinery
//! promises -- inside a forcewake-free band, inside the mapped window, no
//! address declared twice, no name declared twice -- are checked by a test over
//! *all* of them rather than over the ones someone remembered to list.
//!
//! The grouping is by hardware block, matching the submodules.

use super::{Register, ddi, dpll, interrupt, pipe, port};

/// The ddi block's registers, in declaration order.
pub(crate) const DDI: &[Register] = &[
    ddi::TRANS_HTOTAL_A,
    ddi::TRANS_HBLANK_A,
    ddi::TRANS_HSYNC_A,
    ddi::TRANS_VTOTAL_A,
    ddi::TRANS_VBLANK_A,
    ddi::TRANS_VSYNC_A,
    ddi::TRANS_HTOTAL_B,
    ddi::TRANS_HBLANK_B,
    ddi::TRANS_HSYNC_B,
    ddi::TRANS_VTOTAL_B,
    ddi::TRANS_VBLANK_B,
    ddi::TRANS_VSYNC_B,
    ddi::TRANS_HTOTAL_C,
    ddi::TRANS_HBLANK_C,
    ddi::TRANS_HSYNC_C,
    ddi::TRANS_VTOTAL_C,
    ddi::TRANS_VBLANK_C,
    ddi::TRANS_VSYNC_C,
    ddi::TRANS_HTOTAL_D,
    ddi::TRANS_HBLANK_D,
    ddi::TRANS_HSYNC_D,
    ddi::TRANS_VTOTAL_D,
    ddi::TRANS_VBLANK_D,
    ddi::TRANS_VSYNC_D,
    ddi::TRANS_CLK_SEL_A,
    ddi::TRANS_CLK_SEL_B,
    ddi::TRANS_CLK_SEL_C,
    ddi::TRANS_CLK_SEL_D,
    ddi::TRANS_DDI_FUNC_CTL_A,
    ddi::TRANS_DDI_FUNC_CTL_B,
    ddi::TRANS_DDI_FUNC_CTL_C,
    ddi::TRANS_DDI_FUNC_CTL_D,
    ddi::DDI_BUF_CTL_A,
    ddi::DDI_BUF_CTL_B,
    ddi::DDI_BUF_TRANS_LO_A0,
    ddi::DDI_BUF_TRANS_HI_A0,
    ddi::DDI_BUF_TRANS_LO_A1,
    ddi::DDI_BUF_TRANS_HI_A1,
    ddi::DDI_BUF_TRANS_LO_A2,
    ddi::DDI_BUF_TRANS_HI_A2,
    ddi::DDI_BUF_TRANS_LO_A3,
    ddi::DDI_BUF_TRANS_HI_A3,
    ddi::DDI_BUF_TRANS_LO_A4,
    ddi::DDI_BUF_TRANS_HI_A4,
    ddi::DDI_BUF_TRANS_LO_A5,
    ddi::DDI_BUF_TRANS_HI_A5,
    ddi::DDI_BUF_TRANS_LO_A6,
    ddi::DDI_BUF_TRANS_HI_A6,
    ddi::DDI_BUF_TRANS_LO_A7,
    ddi::DDI_BUF_TRANS_HI_A7,
    ddi::DDI_BUF_TRANS_LO_A8,
    ddi::DDI_BUF_TRANS_HI_A8,
    ddi::DDI_BUF_TRANS_LO_A9,
    ddi::DDI_BUF_TRANS_HI_A9,
    ddi::DDI_BUF_TRANS_LO_B0,
    ddi::DDI_BUF_TRANS_HI_B0,
    ddi::DDI_BUF_TRANS_LO_B1,
    ddi::DDI_BUF_TRANS_HI_B1,
    ddi::DDI_BUF_TRANS_LO_B2,
    ddi::DDI_BUF_TRANS_HI_B2,
    ddi::DDI_BUF_TRANS_LO_B3,
    ddi::DDI_BUF_TRANS_HI_B3,
    ddi::DDI_BUF_TRANS_LO_B4,
    ddi::DDI_BUF_TRANS_HI_B4,
    ddi::DDI_BUF_TRANS_LO_B5,
    ddi::DDI_BUF_TRANS_HI_B5,
    ddi::DDI_BUF_TRANS_LO_B6,
    ddi::DDI_BUF_TRANS_HI_B6,
    ddi::DDI_BUF_TRANS_LO_B7,
    ddi::DDI_BUF_TRANS_HI_B7,
    ddi::DDI_BUF_TRANS_LO_B8,
    ddi::DDI_BUF_TRANS_HI_B8,
    ddi::DDI_BUF_TRANS_LO_B9,
    ddi::DDI_BUF_TRANS_HI_B9,
];

/// The dpll block's registers, in declaration order.
pub(crate) const DPLL: &[Register] = &[
    dpll::DPLL0_CFGCR0,
    dpll::DPLL0_CFGCR1,
    dpll::DPLL1_CFGCR0,
    dpll::DPLL1_CFGCR1,
    dpll::DPLL0_ENABLE,
    dpll::DPLL1_ENABLE,
    dpll::ICL_DPCLKA_CFGCR0,
];

/// The interrupt block's registers, in declaration order.
pub(crate) const INTERRUPT: &[Register] = &[
    interrupt::DEIMR,
    interrupt::DEIIR,
    interrupt::DEIER,
    interrupt::DISPLAY_INT_CTL,
    interrupt::GEN8_DE_PIPE_IMR_A,
    interrupt::GEN8_DE_PIPE_IIR_A,
    interrupt::GEN8_DE_PIPE_IER_A,
    interrupt::GEN8_DE_PIPE_IMR_B,
    interrupt::GEN8_DE_PIPE_IIR_B,
    interrupt::GEN8_DE_PIPE_IER_B,
    interrupt::GEN8_DE_PIPE_IMR_C,
    interrupt::GEN8_DE_PIPE_IIR_C,
    interrupt::GEN8_DE_PIPE_IER_C,
    interrupt::GEN8_DE_PIPE_IMR_D,
    interrupt::GEN8_DE_PIPE_IIR_D,
    interrupt::GEN8_DE_PIPE_IER_D,
    interrupt::SDEIMR,
    interrupt::SDEIIR,
    interrupt::SDEIER,
];

/// The pipe block's registers, in declaration order.
pub(crate) const PIPE: &[Register] = &[
    pipe::PIPECONF_A,
    pipe::PIPECONF_B,
    pipe::PIPECONF_C,
    pipe::PIPECONF_D,
    pipe::PIPESRC_A,
    pipe::PIPESRC_B,
    pipe::PIPESRC_C,
    pipe::PIPESRC_D,
    pipe::PIPEDSL_A,
    pipe::PIPEDSL_B,
    pipe::PIPEDSL_C,
    pipe::PIPEDSL_D,
    pipe::PIPESTAT_A,
    pipe::PIPESTAT_B,
    pipe::PIPESTAT_C,
    pipe::PIPESTAT_D,
    pipe::PIPE_MISC_A,
    pipe::PIPE_MISC_B,
    pipe::PIPE_MISC_C,
    pipe::PIPE_MISC_D,
    pipe::PLANE_CTL_A,
    pipe::PLANE_CTL_B,
    pipe::PLANE_CTL_C,
    pipe::PLANE_CTL_D,
    pipe::PLANE_STRIDE_A,
    pipe::PLANE_STRIDE_B,
    pipe::PLANE_STRIDE_C,
    pipe::PLANE_STRIDE_D,
    pipe::PLANE_POS_A,
    pipe::PLANE_POS_B,
    pipe::PLANE_POS_C,
    pipe::PLANE_POS_D,
    pipe::PLANE_SIZE_A,
    pipe::PLANE_SIZE_B,
    pipe::PLANE_SIZE_C,
    pipe::PLANE_SIZE_D,
    pipe::PLANE_OFFSET_A,
    pipe::PLANE_OFFSET_B,
    pipe::PLANE_OFFSET_C,
    pipe::PLANE_OFFSET_D,
    pipe::PLANE_SURF_A,
    pipe::PLANE_SURF_B,
    pipe::PLANE_SURF_C,
    pipe::PLANE_SURF_D,
    pipe::PLANE_SURFLIVE_A,
    pipe::PLANE_SURFLIVE_B,
    pipe::PLANE_SURFLIVE_C,
    pipe::PLANE_SURFLIVE_D,
    pipe::PLANE_COLOR_CTL_A,
    pipe::PLANE_COLOR_CTL_B,
    pipe::PLANE_COLOR_CTL_C,
    pipe::PLANE_COLOR_CTL_D,
    pipe::PLANE_BUF_CFG_A,
    pipe::PLANE_BUF_CFG_B,
    pipe::PLANE_BUF_CFG_C,
    pipe::PLANE_BUF_CFG_D,
    pipe::PLANE_WM_0_A,
    pipe::PLANE_WM_1_A,
    pipe::PLANE_WM_2_A,
    pipe::PLANE_WM_3_A,
    pipe::PLANE_WM_4_A,
    pipe::PLANE_WM_5_A,
    pipe::PLANE_WM_6_A,
    pipe::PLANE_WM_7_A,
    pipe::PLANE_WM_0_B,
    pipe::PLANE_WM_1_B,
    pipe::PLANE_WM_2_B,
    pipe::PLANE_WM_3_B,
    pipe::PLANE_WM_4_B,
    pipe::PLANE_WM_5_B,
    pipe::PLANE_WM_6_B,
    pipe::PLANE_WM_7_B,
    pipe::PLANE_WM_0_C,
    pipe::PLANE_WM_1_C,
    pipe::PLANE_WM_2_C,
    pipe::PLANE_WM_3_C,
    pipe::PLANE_WM_4_C,
    pipe::PLANE_WM_5_C,
    pipe::PLANE_WM_6_C,
    pipe::PLANE_WM_7_C,
    pipe::PLANE_WM_0_D,
    pipe::PLANE_WM_1_D,
    pipe::PLANE_WM_2_D,
    pipe::PLANE_WM_3_D,
    pipe::PLANE_WM_4_D,
    pipe::PLANE_WM_5_D,
    pipe::PLANE_WM_6_D,
    pipe::PLANE_WM_7_D,
];

/// The port block's registers, in declaration order.
pub(crate) const PORT: &[Register] = &[
    port::PORT_CL_DW10_A,
    port::PORT_CL_DW10_B,
    port::PORT_TX_DW2_GRP_A,
    port::PORT_TX_DW2_GRP_B,
    port::PORT_TX_DW4_LN0_A,
    port::PORT_TX_DW4_LN1_A,
    port::PORT_TX_DW4_LN2_A,
    port::PORT_TX_DW4_LN3_A,
    port::PORT_TX_DW4_LN0_B,
    port::PORT_TX_DW4_LN1_B,
    port::PORT_TX_DW4_LN2_B,
    port::PORT_TX_DW4_LN3_B,
    port::PORT_TX_DW5_GRP_A,
    port::PORT_TX_DW5_GRP_B,
    port::PORT_TX_DW7_GRP_A,
    port::PORT_TX_DW7_GRP_B,
];

/// Every table above, for a test that has to walk all of them.
pub(crate) const ALL: &[&[Register]] = &[
    DDI,
    DPLL,
    INTERRUPT,
    PIPE,
    PORT,
];

#[cfg(test)]
mod tests;
