[package]
name = "tk-axdriver-watchdog"
version = "0.1.0"
repository.workspace = true
rust-version.workspace = true
edition = "2024"
license = "Apache-2.0"
publish = false
[lib]
name = "axdriver_watchdog"
[package.metadata.thekernel]
layer = "platform"
[package.metadata.thekernel.host-test]
selected = true
