[package]
publish.workspace = true
rust-version.workspace = true
name = "tk-axmm"
version = "0.1.0"
edition = "2024"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS virtual memory management module"
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository.workspace = true

[features]
copy = ["page_table_multiarch/copy-from"]

[lib]
name = "axmm"
path = "src/lib.rs"

[dependencies]
axalloc = { package = "tk-axalloc", path = "../tk-axalloc", version = "0.1.0" }
axerrno = "0.2"
axhal = { package = "tk-axhal", path = "../tk-axhal", version = "0.1.0", features = ["paging"] }
kspin = "0.1"
lazyinit = "0.2"
log = "0.4"
memory_addr = "0.4"
memory_set = { package = "tk-memory-set", path = "../tk-memory-set", version = "0.1.0", features = ["axerrno"] }
page_table_multiarch = { package = "tk-page-table-multiarch", path = "../tk-page-table-multiarch", version = "0.1.0", features = ["axerrno"], optional = true }

[package.metadata.thekernel]
layer = "platform"
