// SPDX-License-Identifier: MIT
// Copyright 2026 TheKernel contributors. See ../../LICENSE-MIT.
//
// Small, source-faithful DRM/LinuxKPI printing surface for the imported i915
// code. C varargs are not available to Rust macros after translation, so the
// macros below retain each argument as a typed value and interpret the C
// conversion specifiers here. This deliberately does not turn diagnostics into
// no-ops.

#![allow(unsafe_code, non_camel_case_types, non_snake_case)]

use alloc::{
    ffi::CString,
    format,
    string::{String, ToString},
    vec::Vec,
};
use core::{
    ffi::{CStr, c_char},
    sync::atomic::{AtomicU32, Ordering},
};

pub use crate::linux::fields::{DrmPrinter as drm_printer, DrmPrinter};
use crate::linux::fields::{DrmPrinterLine, VaFormat, VaList};

/// DRM debug categories used by the GT translations.
pub const DRM_UT_CORE: u32 = 0x01;
pub const DRM_UT_DRIVER: u32 = 0x08;
pub const DRM_UT_KMS: u32 = 0x02;
pub const DRM_UT_PRIME: u32 = 0x04;
pub const DRM_UT_ATOMIC: u32 = 0x10;

static DRM_DEBUG_MASK: AtomicU32 = AtomicU32::new(0);

/// Set the categories enabled for `drm_dbg!`/`drm_dbg_printer` diagnostics.
/// The Linux default is zero; the platform may set this from its DRM debug
/// policy without changing the imported driver source.
pub fn drm_debug_set(mask: u32) {
    DRM_DEBUG_MASK.store(mask, Ordering::Release);
}

#[allow(non_snake_case)]
pub fn drm_debug_enabled(category: u32) -> bool {
    DRM_DEBUG_MASK.load(Ordering::Acquire) & category != 0
}

/// Destination severity for the built-in printer sink.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DrmLogLevel {
    Debug,
    Info,
    Warn,
    Error,
}

#[derive(Clone, Debug)]
pub enum FormatValue {
    Signed(i128),
    Unsigned(u128),
    Pointer(usize),
    Text(String),
}

/// Values accepted by the C-style formatter. Keep this trait narrow and
/// explicit: imported printf sites must pass real typed values, not strings
/// generated by lossy source rewriting.
pub trait CFormatArg {
    #[doc(hidden)]
    fn c_format_value(&self) -> FormatValue;
}

macro_rules! signed_format_args {
    ($($ty:ty),+ $(,)?) => {$ (
        impl CFormatArg for $ty {
            fn c_format_value(&self) -> FormatValue {
                FormatValue::Signed(*self as i128)
            }
        }
    )+};
}

macro_rules! unsigned_format_args {
    ($($ty:ty),+ $(,)?) => {$ (
        impl CFormatArg for $ty {
            fn c_format_value(&self) -> FormatValue {
                FormatValue::Unsigned(*self as u128)
            }
        }
    )+};
}

signed_format_args!(i8, i16, i32, i64, i128, isize);
unsigned_format_args!(u8, u16, u32, u64, u128, usize);

impl CFormatArg for bool {
    fn c_format_value(&self) -> FormatValue {
        FormatValue::Unsigned(u128::from(*self))
    }
}

impl CFormatArg for char {
    fn c_format_value(&self) -> FormatValue {
        FormatValue::Unsigned(*self as u32 as u128)
    }
}

impl CFormatArg for str {
    fn c_format_value(&self) -> FormatValue {
        FormatValue::Text(self.into())
    }
}

impl CFormatArg for String {
    fn c_format_value(&self) -> FormatValue {
        FormatValue::Text(self.clone())
    }
}

impl<const N: usize> CFormatArg for [c_char; N] {
    fn c_format_value(&self) -> FormatValue {
        let bytes = self
            .iter()
            .map(|ch| *ch as u8)
            .take_while(|ch| *ch != 0)
            .collect::<Vec<_>>();
        FormatValue::Text(String::from_utf8_lossy(&bytes).into_owned())
    }
}

impl<T: CFormatArg + ?Sized> CFormatArg for &T {
    fn c_format_value(&self) -> FormatValue {
        (**self).c_format_value()
    }
}

impl<T> CFormatArg for *const T {
    fn c_format_value(&self) -> FormatValue {
        FormatValue::Pointer(*self as usize)
    }
}

impl<T> CFormatArg for *mut T {
    fn c_format_value(&self) -> FormatValue {
        FormatValue::Pointer(*self as usize)
    }
}

#[derive(Default)]
struct PrintSpec {
    left: bool,
    plus: bool,
    space: bool,
    alternate: bool,
    zero: bool,
    width: Option<usize>,
    precision: Option<usize>,
}

fn take_value<'a>(args: &'a [&dyn CFormatArg], next: &mut usize) -> Option<FormatValue> {
    let value = args.get(*next)?.c_format_value();
    *next += 1;
    Some(value)
}

fn decimal_value(value: &FormatValue, signed: bool) -> (u128, bool) {
    match value {
        FormatValue::Signed(value) if signed => (value.unsigned_abs(), *value < 0),
        FormatValue::Signed(value) => (*value as u128, false),
        FormatValue::Unsigned(value) if signed => (*value as i128 as u128, (*value as i128) < 0),
        FormatValue::Unsigned(value) => (*value, false),
        FormatValue::Pointer(value) => (*value as u128, false),
        FormatValue::Text(value) => (value.parse::<u128>().unwrap_or(0), false),
    }
}

fn digits(mut value: u128, radix: u32, upper: bool) -> String {
    let alphabet = if upper {
        b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    } else {
        b"0123456789abcdefghijklmnopqrstuvwxyz"
    };
    if value == 0 {
        return "0".into();
    }
    let mut reversed = Vec::new();
    while value != 0 {
        reversed.push(alphabet[(value % radix as u128) as usize]);
        value /= radix as u128;
    }
    let mut result = String::with_capacity(reversed.len());
    for byte in reversed.into_iter().rev() {
        result.push(byte as char);
    }
    result
}

fn pad_text(text: &str, spec: &PrintSpec) -> String {
    let text = match spec.precision {
        Some(precision) => text.chars().take(precision).collect::<String>(),
        None => text.into(),
    };
    let width = spec.width.unwrap_or(0);
    let padding = width.saturating_sub(text.chars().count());
    if spec.left {
        let mut result = text;
        result.extend(core::iter::repeat_n(' ', padding));
        result
    } else {
        let mut result = String::with_capacity(width.max(text.len()));
        result.extend(core::iter::repeat_n(' ', padding));
        result.push_str(&text);
        result
    }
}

fn format_number(
    value: u128,
    negative: bool,
    radix: u32,
    upper: bool,
    pointer: bool,
    spec: &PrintSpec,
) -> String {
    let mut body = digits(value, radix, upper);
    if let Some(precision) = spec.precision {
        if precision == 0 && value == 0 {
            body.clear();
        }
        if body.len() < precision {
            let mut zeroes = String::with_capacity(precision - body.len());
            zeroes.extend(core::iter::repeat_n('0', precision - body.len()));
            zeroes.push_str(&body);
            body = zeroes;
        }
    }

    let sign = if negative {
        "-"
    } else if spec.plus {
        "+"
    } else if spec.space {
        " "
    } else {
        ""
    };
    let prefix = if pointer {
        "0x"
    } else if spec.alternate && radix == 16 && value != 0 {
        if upper { "0X" } else { "0x" }
    } else if spec.alternate && radix == 8 && !body.starts_with('0') {
        "0"
    } else {
        ""
    };
    let width = spec.width.unwrap_or(0);
    let total = sign.len() + prefix.len() + body.len();
    let padding = width.saturating_sub(total);
    let use_zero = spec.zero && !spec.left && spec.precision.is_none();
    let mut result = String::with_capacity(width.max(total));
    if !spec.left && !use_zero {
        result.extend(core::iter::repeat_n(' ', padding));
    }
    result.push_str(sign);
    result.push_str(prefix);
    if use_zero {
        result.extend(core::iter::repeat_n('0', padding));
    }
    result.push_str(&body);
    if spec.left {
        result.extend(core::iter::repeat_n(' ', padding));
    }
    result
}

fn c_string(pointer: usize) -> String {
    if pointer == 0 {
        return "(null)".into();
    }
    // C `%s` explicitly promises a valid nul-terminated string at this point.
    let cstr = unsafe { CStr::from_ptr(pointer as *const c_char) };
    cstr.to_string_lossy().into_owned()
}

fn error_pointer(pointer: usize) -> String {
    let error = pointer as isize as i32;
    let name = match error {
        -1 => "EPERM",
        -2 => "ENOENT",
        -4 => "EINTR",
        -5 => "EIO",
        -6 => "ENXIO",
        -11 => "EAGAIN",
        -12 => "ENOMEM",
        -13 => "EACCES",
        -14 => "EFAULT",
        -16 => "EBUSY",
        -19 => "ENODEV",
        -22 => "EINVAL",
        -28 => "ENOSPC",
        -32 => "EPIPE",
        -35 => "EDEADLK",
        -71 => "EPROTO",
        -75 => "EOVERFLOW",
        -110 => "ETIMEDOUT",
        _ => return format!("{error}"),
    };
    format!("-{name}")
}

fn render_conversion(
    value: &FormatValue,
    conversion: char,
    spec: &PrintSpec,
    error_ptr: bool,
) -> String {
    match conversion {
        's' => {
            let text = match value {
                FormatValue::Text(text) => text.clone(),
                FormatValue::Pointer(pointer) => c_string(*pointer),
                other => {
                    let (value, _) = decimal_value(other, false);
                    format!("{value}")
                }
            };
            pad_text(&text, spec)
        }
        'c' => {
            let (value, _) = decimal_value(value, false);
            let character = char::from_u32(value as u32).unwrap_or('\u{fffd}');
            pad_text(&character.to_string(), spec)
        }
        'p' if error_ptr => {
            let pointer = match value {
                FormatValue::Pointer(pointer) => *pointer,
                FormatValue::Signed(value) => *value as usize,
                FormatValue::Unsigned(value) => *value as usize,
                FormatValue::Text(_) => 0,
            };
            pad_text(&error_pointer(pointer), spec)
        }
        'p' => {
            let pointer = match value {
                FormatValue::Pointer(pointer) => *pointer as u128,
                FormatValue::Signed(value) => *value as usize as u128,
                FormatValue::Unsigned(value) => *value as usize as u128,
                FormatValue::Text(_) => 0,
            };
            format_number(pointer, false, 16, false, true, spec)
        }
        'd' | 'i' => {
            let (value, negative) = decimal_value(value, true);
            format_number(value, negative, 10, false, false, spec)
        }
        'u' => {
            let (value, _) = decimal_value(value, false);
            format_number(value, false, 10, false, false, spec)
        }
        'o' => {
            let (value, _) = decimal_value(value, false);
            format_number(value, false, 8, false, false, spec)
        }
        'x' | 'X' => {
            let (value, _) = decimal_value(value, false);
            format_number(value, false, 16, conversion == 'X', false, spec)
        }
        // Unknown conversions are preserved visibly instead of silently
        // dropping a value. No current GT printf site needs floating point.
        other => format!("%{other}({value:?})"),
    }
}

fn parse_c_spec(bytes: &[u8], start: usize) -> (usize, PrintSpec, Option<char>, bool) {
    let mut i = start + 1;
    let mut spec = PrintSpec::default();
    loop {
        match bytes.get(i).copied() {
            Some(b'-') => spec.left = true,
            Some(b'+') => spec.plus = true,
            Some(b' ') => spec.space = true,
            Some(b'#') => spec.alternate = true,
            Some(b'0') => spec.zero = true,
            _ => break,
        }
        i += 1;
    }
    let width_start = i;
    while bytes.get(i).is_some_and(|byte| byte.is_ascii_digit()) {
        i += 1;
    }
    if width_start != i {
        spec.width = core::str::from_utf8(&bytes[width_start..i])
            .ok()
            .and_then(|s| s.parse().ok());
    }
    if bytes.get(i) == Some(&b'.') {
        i += 1;
        let precision_start = i;
        while bytes.get(i).is_some_and(|byte| byte.is_ascii_digit()) {
            i += 1;
        }
        spec.precision = if precision_start == i {
            Some(0)
        } else {
            core::str::from_utf8(&bytes[precision_start..i])
                .ok()
                .and_then(|s| s.parse().ok())
        };
    }
    // C integer length modifiers do not change the Rust value representation;
    // they only affect the expected ABI width, already fixed by the argument.
    while matches!(bytes.get(i), Some(b'h' | b'l' | b'z' | b't' | b'j' | b'L')) {
        i += 1;
    }
    let conversion = bytes.get(i).copied().map(char::from);
    if conversion.is_some() {
        i += 1;
    }
    let error_ptr = conversion == Some('p') && bytes.get(i) == Some(&b'e');
    if error_ptr {
        i += 1;
    }
    (i, spec, conversion, error_ptr)
}

fn render_rust_placeholder(value: &FormatValue, spec_text: &str) -> String {
    let mut spec = PrintSpec::default();
    let mut conversion = 's';
    let raw = spec_text.trim_start_matches(':');
    if raw == "p" {
        conversion = 'p';
    } else if raw.ends_with('x') || raw.ends_with('X') {
        conversion = raw.chars().last().unwrap_or('x');
        spec.alternate = raw.contains('#');
        spec.zero = raw.contains('0');
        let width = raw
            .trim_start_matches('#')
            .trim_start_matches('0')
            .trim_end_matches(['x', 'X']);
        spec.width = width.parse().ok();
    } else if !raw.is_empty() {
        conversion = 's';
        spec.width = raw
            .trim_start_matches('>')
            .trim_start_matches('<')
            .parse()
            .ok();
        spec.left = raw.starts_with('<');
    }
    match conversion {
        'p' => {
            let pointer = match value {
                FormatValue::Pointer(pointer) => *pointer as u128,
                FormatValue::Signed(value) => *value as usize as u128,
                FormatValue::Unsigned(value) => *value as usize as u128,
                FormatValue::Text(_) => 0,
            };
            format_number(pointer, false, 16, false, true, &spec)
        }
        'x' | 'X' => {
            let (number, negative) = decimal_value(value, false);
            format_number(number, negative, 16, conversion == 'X', false, &spec)
        }
        _ => match value {
            FormatValue::Text(text) => pad_text(text, &spec),
            FormatValue::Signed(value) => pad_text(&format!("{value}"), &spec),
            FormatValue::Unsigned(value) => pad_text(&format!("{value}"), &spec),
            FormatValue::Pointer(pointer) => pad_text(&format!("0x{pointer:x}"), &spec),
        },
    }
}

/// Render a mixed translated format string: upstream C `%` directives and
/// Rust `{}` placeholders are both retained by the source-order port.
pub fn format_message(format: &str, args: &[&dyn CFormatArg]) -> String {
    format_message_impl(format, args, true)
}

/// Render a C `printf` format. Braces have no special meaning in C format
/// strings, so preserve literal `{...}` text while consuming only `%` fields.
pub fn format_c_message(format: &str, args: &[&dyn CFormatArg]) -> String {
    format_message_impl(format, args, false)
}

fn format_message_impl(format: &str, args: &[&dyn CFormatArg], rust_braces: bool) -> String {
    let bytes = format.as_bytes();
    let mut output = String::with_capacity(format.len() + args.len() * 8);
    let mut i = 0;
    let mut next = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'%' if bytes.get(i + 1) == Some(&b'%') => {
                output.push('%');
                i += 2;
            }
            b'%' => {
                let (end, spec, conversion, error_ptr) = parse_c_spec(bytes, i);
                let Some(conversion) = conversion else {
                    output.push('%');
                    i += 1;
                    continue;
                };
                if let Some(value) = take_value(args, &mut next) {
                    output.push_str(&render_conversion(&value, conversion, &spec, error_ptr));
                } else {
                    let directive = core::str::from_utf8(&bytes[i..end]).unwrap_or("%?");
                    output.push_str(directive);
                }
                i = end;
            }
            b'{' if rust_braces && bytes.get(i + 1) == Some(&b'{') => {
                output.push('{');
                i += 2;
            }
            b'}' if rust_braces && bytes.get(i + 1) == Some(&b'}') => {
                output.push('}');
                i += 2;
            }
            b'{' if rust_braces => {
                if let Some(close) = bytes[i + 1..].iter().position(|byte| *byte == b'}') {
                    let end = i + 1 + close;
                    let spec_text = core::str::from_utf8(&bytes[i + 1..end]).unwrap_or("");
                    if let Some(value) = take_value(args, &mut next) {
                        output.push_str(&render_rust_placeholder(&value, spec_text));
                    } else {
                        output.push_str(&format[i..=end]);
                    }
                    i = end + 1;
                } else {
                    output.push('{');
                    i += 1;
                }
            }
            _ => {
                let ch = format[i..].chars().next().expect("valid string boundary");
                output.push(ch);
                i += ch.len_utf8();
            }
        }
    }
    output
}

fn c_int_length(bytes: usize) -> i32 {
    bytes.min(i32::MAX as usize) as i32
}

/// Write a C `snprintf` result into a caller-owned character buffer.
///
/// `snprintf` returns the number of bytes that would have been produced,
/// excluding the trailing NUL. A zero-sized buffer is not dereferenced; for a
/// nonzero size a valid destination pointer is required, as in the C API.
pub unsafe fn c_snprintf(buffer: *mut c_char, size: usize, text: &str) -> i32 {
    if size == 0 {
        return c_int_length(text.len());
    }
    if buffer.is_null() {
        panic!("snprintf called with a null buffer and nonzero size");
    }

    let copied = text.len().min(size - 1);
    if copied != 0 {
        unsafe { core::ptr::copy_nonoverlapping(text.as_ptr(), buffer.cast::<u8>(), copied) };
    }
    unsafe { buffer.add(copied).write(0) };
    c_int_length(text.len())
}

/// Write a C `scnprintf` result. Unlike `snprintf`, it returns the number of
/// bytes actually copied, never the would-have-written length.
pub unsafe fn c_scnprintf(buffer: *mut c_char, size: usize, text: &str) -> i32 {
    if size == 0 {
        return 0;
    }
    if buffer.is_null() {
        panic!("scnprintf called with a null buffer and nonzero size");
    }

    let copied = text.len().min(size - 1);
    if copied != 0 {
        unsafe { core::ptr::copy_nonoverlapping(text.as_ptr(), buffer.cast::<u8>(), copied) };
    }
    unsafe { buffer.add(copied).write(0) };
    c_int_length(copied)
}

// Rust has no stable C-variadic function definitions. Preserve Linux's
// variadic call shape for translated `snprintf!` sites with a typed macro;
// function-shaped callsites still need the mechanical `!` adaptation rather
// than an unfaithful stub.
macro_rules! snprintf {
    ($buffer:expr, $size:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __buffer = $buffer as *mut core::ffi::c_char;
        let __size = ($size) as usize;
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __text = $crate::linux_print::format_c_message($format, __args);
        unsafe { $crate::linux_print::c_snprintf(__buffer, __size, &__text) }
    }};
}

macro_rules! scnprintf {
    ($buffer:expr, $size:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __buffer = $buffer as *mut core::ffi::c_char;
        let __size = ($size) as usize;
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __text = $crate::linux_print::format_c_message($format, __args);
        unsafe { $crate::linux_print::c_scnprintf(__buffer, __size, &__text) }
    }};
}

unsafe extern "C" fn linuxkpi_printer_puts(printer: *mut DrmPrinter, text: *const c_char) {
    if printer.is_null() || text.is_null() {
        return;
    }
    let text = unsafe { CStr::from_ptr(text) }.to_string_lossy();
    let prefix = if unsafe { (*printer).prefix.is_null() } {
        ""
    } else {
        unsafe { CStr::from_ptr((*printer).prefix) }
            .to_str()
            .unwrap_or("<non-UTF8 prefix>")
    };
    let mut message = String::with_capacity(prefix.len() + text.len() + 1);
    if !prefix.is_empty() {
        message.push_str(prefix);
        if !prefix.ends_with(' ') && !text.starts_with('\n') {
            message.push(' ');
        }
    }
    message.push_str(&text);
    drm_log_at(DrmLogLevel::Info, "drm_printer", file!(), line!(), &message);
}

unsafe extern "C" fn linuxkpi_printer_printfn(printer: *mut DrmPrinter, value: *mut VaFormat) {
    if printer.is_null() || value.is_null() || unsafe { (*value).fmt.is_null() } {
        return;
    }
    let format = unsafe { CStr::from_ptr((*value).fmt) }.to_string_lossy();
    let marker = format!("{format}<unparsed Linux va_list delegated to drm_printer callback>");
    drm_printer_write(printer, &marker);
}

/// Append formatted text via Linux `drm_printer.puts`. The C printer ABI is
/// preserved; typed Rust format conversion is only used at translated call
/// sites where the argument tuple is explicit.
pub fn drm_printer_write(printer: *mut drm_printer, text: &str) {
    if printer.is_null() {
        axlog::error!("i915 drm_printf received a null drm_printer");
        return;
    }
    let Ok(text) = CString::new(text) else {
        axlog::error!("i915 drm_printf string contained an interior NUL");
        return;
    };
    if let Some(puts) = unsafe { (*printer).puts } {
        unsafe { puts(printer, text.as_ptr()) };
    } else {
        drm_log_at(
            DrmLogLevel::Info,
            "drm_printer",
            file!(),
            line!(),
            text.to_str().unwrap_or("<non-UTF8 drm_printf output>"),
        );
    }
}

/// Create a DRM debug printer. The device argument is retained in the API for
/// source compatibility; the category and requested prefix control output.
pub fn drm_dbg_printer<D>(drm: &mut D, category: u32, prefix: *const c_char) -> drm_printer {
    let enabled = drm_debug_enabled(category);
    drm_printer {
        printfn: Some(linuxkpi_printer_printfn),
        puts: if enabled {
            Some(linuxkpi_printer_puts)
        } else {
            None
        },
        arg: core::ptr::null_mut(),
        origin: (drm as *mut D).cast(),
        prefix,
        line: DrmPrinterLine {
            series: 0,
            counter: 0,
        },
    }
}

/// Linux `drm_vprintf()` takes a C `va_list`. Rust's stable ABI has no
/// equivalent, so the translated source must not pretend it consumed the
/// arguments. Emit an explicit diagnostic marker until that source site is
/// adapted to a typed formatter.
pub unsafe fn drm_vprintf(printer: *mut drm_printer, header: *const c_char, ap: *mut VaList) {
    if printer.is_null() {
        return;
    }
    if let Some(printfn) = unsafe { (*printer).printfn } {
        let mut value = VaFormat {
            fmt: header,
            va: ap,
        };
        unsafe { printfn(printer, &mut value) };
    }
}

fn log_message(level: DrmLogLevel, prefix: &str, file: &str, line: u32, message: &str) {
    match level {
        DrmLogLevel::Debug => axlog::debug!("{prefix} {file}:{line}: {message}"),
        DrmLogLevel::Info => axlog::info!("{prefix} {file}:{line}: {message}"),
        DrmLogLevel::Warn => axlog::warn!("{prefix} {file}:{line}: {message}"),
        DrmLogLevel::Error => axlog::error!("{prefix} {file}:{line}: {message}"),
    }
}

#[doc(hidden)]
pub fn drm_log_at(level: DrmLogLevel, prefix: &str, file: &str, line: u32, message: &str) {
    log_message(level, prefix, file, line, message);
}

macro_rules! drm_printf {
    ($printer:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        let __printer = $printer as *mut $crate::linux_print::drm_printer;
        $crate::linux_print::drm_printer_write(__printer, &__message);
    }};
}

macro_rules! drm_err {
    ($device:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __device = $device;
        let _ = __device;
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Error,
            "i915 DRM error",
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! drm_err_once {
    ($device:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        static __WARNED: core::sync::atomic::AtomicBool =
            core::sync::atomic::AtomicBool::new(false);
        if !__WARNED.swap(true, core::sync::atomic::Ordering::Relaxed) {
            drm_err!($device, $format $(, $argument)*);
        }
    }};
}

macro_rules! drm_dbg {
    ($device:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __device = $device;
        let _ = __device;
        if $crate::linux_print::drm_debug_enabled($crate::linux_print::DRM_UT_DRIVER) {
            let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
                $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
            ];
            let __message = $crate::linux_print::format_message($format, __args);
            $crate::linux_print::drm_log_at(
                $crate::linux_print::DrmLogLevel::Debug,
                "i915 DRM debug",
                file!(),
                line!(),
                &__message,
            );
        }
    }};
}

macro_rules! drm_notice {
    ($device:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __device = $device;
        let _ = __device;
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Info,
            "i915 DRM notice",
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! drm_warn {
    ($device:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __device = $device;
        let _ = __device;
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Warn,
            "i915 DRM warning",
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! gt_dbg {
    ($gt:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __gt = $gt;
        let _ = __gt;
        if $crate::linux_print::drm_debug_enabled($crate::linux_print::DRM_UT_DRIVER) {
            let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
                $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
            ];
            let __message = $crate::linux_print::format_message($format, __args);
            $crate::linux_print::drm_log_at(
                $crate::linux_print::DrmLogLevel::Debug,
                "i915 GT debug",
                file!(),
                line!(),
                &__message,
            );
        }
    }};
}

macro_rules! guc_err {
    ($guc:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __guc = $guc;
        let _ = __guc;
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Error,
            "i915 GuC error",
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! pr_err {
    ($format:expr $(, $argument:expr)* $(,)?) => {{
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Error,
            "i915",
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! pr_info {
    ($format:expr $(, $argument:expr)* $(,)?) => {{
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Info,
            "kernel info",
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! GEM_TRACE_ERR {
    ($format:expr $(, $argument:expr)* $(,)?) => {{
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Error,
            "i915 GEM trace",
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! guc_warn {
    ($guc:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __guc = $guc;
        let _ = __guc;
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Warn,
            "i915 GuC warning",
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! gt_err {
    ($gt:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __gt = $gt;
        let __id = unsafe { (*__gt).info.id };
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Error,
            &alloc::format!("GT{__id}"),
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! gt_notice {
    ($gt:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __gt = $gt;
        let __id = unsafe { (*__gt).info.id };
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Info,
            &alloc::format!("GT{__id}"),
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! gt_dbg {
    ($gt:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __gt = $gt;
        if $crate::linux_print::drm_debug_enabled($crate::linux_print::DRM_UT_DRIVER) {
            let __id = unsafe { (*__gt).info.id };
            let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
                $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
            ];
            let __message = $crate::linux_print::format_message($format, __args);
            $crate::linux_print::drm_log_at(
                $crate::linux_print::DrmLogLevel::Debug,
                &alloc::format!("GT{__id}"),
                file!(),
                line!(),
                &__message,
            );
        }
    }};
}

macro_rules! guc_probe_error {
    ($guc:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __guc = $guc;
        let __gt = unsafe {
            $crate::linux::i915::guc_to_gt(__guc as *mut _)
        };
        let __id = unsafe { (*__gt).info.id };
        let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
            $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
        ];
        let __message = $crate::linux_print::format_message($format, __args);
        $crate::linux_print::drm_log_at(
            $crate::linux_print::DrmLogLevel::Error,
            &alloc::format!("GT{__id} GuC probe"),
            file!(),
            line!(),
            &__message,
        );
    }};
}

macro_rules! guc_dbg {
    ($guc:expr, $format:expr $(, $argument:expr)* $(,)?) => {{
        let __guc = $guc;
        let _ = __guc;
        if $crate::linux_print::drm_debug_enabled($crate::linux_print::DRM_UT_DRIVER) {
            let __args: &[&dyn $crate::linux_print::CFormatArg] = &[
                $(&($argument) as &dyn $crate::linux_print::CFormatArg),*
            ];
            let __message = $crate::linux_print::format_message($format, __args);
            $crate::linux_print::drm_log_at(
                $crate::linux_print::DrmLogLevel::Debug,
                "i915 GuC debug",
                file!(),
                line!(),
                &__message,
            );
        }
    }};
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_linux_printf_formatters_and_rust_placeholders() {
        let args: &[&dyn CFormatArg] = &[&7u32, &0x12u32, &-3i32, &0x1234usize];
        assert_eq!(
            format_message("v=%u x=%08x d=%d p={:#x}", args),
            "v=7 x=00000012 d=-3 p=0x1234"
        );
    }

    #[test]
    fn printer_type_matches_linux_drm_print_abi() {
        assert_eq!(core::mem::size_of::<DrmPrinter>(), 48);
        assert_eq!(core::mem::offset_of!(DrmPrinter, origin), 24);
        assert_eq!(core::mem::offset_of!(DrmPrinter, prefix), 32);
        assert_eq!(core::mem::offset_of!(DrmPrinter, line), 40);
    }

    #[test]
    fn c_printf_preserves_brace_text_and_snprintf_return_contract() {
        let args: &[&dyn CFormatArg] = &[&0x12u32];
        let text = format_c_message("ring:{start:%08x}", args);
        assert_eq!(text, "ring:{start:00000012}");

        let mut buffer = [0 as c_char; 6];
        let would_write = unsafe { c_snprintf(buffer.as_mut_ptr(), buffer.len(), "val=00000012") };
        assert_eq!(would_write, 12);
        assert_eq!(
            unsafe { CStr::from_ptr(buffer.as_ptr()) }.to_str().unwrap(),
            "val=0"
        );

        buffer.fill(0);
        let written = unsafe { c_scnprintf(buffer.as_mut_ptr(), buffer.len(), "val=00000012") };
        assert_eq!(written, 5);
        assert_eq!(
            unsafe { CStr::from_ptr(buffer.as_ptr()) }.to_str().unwrap(),
            "val=0"
        );
    }
}
