//! Full runtime configuration table translated from OpenBSD iwx.
//!
//! Upstream: OpenBSD `sys/dev/pci/if_iwx.c` revision 1.230, complete
//! `iwx_dev_info_table` and `iwx_find_device_cfg()`; `if_iwxvar.h` configuration
//! records and constants. ISC.
//! Copyright (c) 2014, 2016 genua gmbh <info@genua.de>
//!   Author: Stefan Sperling <stsp@openbsd.org>
//! Copyright (c) 2014 Fixup Software Ltd.
//! Copyright (c) 2017, 2019, 2020 Stefan Sperling <stsp@openbsd.org>
//! Copyright (c) 2014 genua mbh <info@genua.de>

/// Intel PCI vendor ID used by the OpenBSD `iwx_devices` table.
pub const INTEL_VENDOR_ID: u16 = 0x8086;
/// AX211 PCI product ID `PCI_PRODUCT_INTEL_WL_22500_16`.
pub const AX211_DEVICE_ID: u16 = 0x54f0;

const PCI_PRODUCT_IDS: &[u16] = &[
    0x2723, 0x02f0, 0xa0f0, 0x34f0, 0x06f0, 0x43f0, 0x3df0, 0x4df0, 0x2725, 0x2726, 0x51f0, 0x7a70,
    0x51f1, 0x7af0, 0x7e40, 0x54f0, 0x7f70, 0x7740,
];

/// Whether a PCI function belongs to OpenBSD's full iwx attach ID list.
// upstream: if_iwx.c iwx_match()
pub const fn matches_pci_device(vendor_id: u16, device_id: u16) -> bool {
    if vendor_id != INTEL_VENDOR_ID {
        return false;
    }
    let mut i = 0;
    while i < PCI_PRODUCT_IDS.len() {
        if PCI_PRODUCT_IDS[i] == device_id {
            return true;
        }
        i += 1;
    }
    false
}

/// Firmware and PNVM selection recorded by `iwx_device_cfg`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FirmwareConfig {
    /// Firmware location using Linux-firmware naming.
    pub firmware: &'static str,
    /// Optional PNVM location using Linux-firmware naming.
    pub pnvm: Option<&'static str>,
    pub tx_with_siso_diversity: bool,
    pub uhb_supported: bool,
    pub xtal_latency: u32,
    pub low_latency_xtal: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DeviceConfig {
    SoGf4Ax411,
    Iwx2axCfgSoGf4A0Long,
    SoGfAx211,
    Iwx2axCfgSoGfA0Long,
    Iwx2axCfgSoJfB0,
    Iwx2axCfgTyGfA0,
    Iwx9560QuC0JfB0Cfg,
    Iwx9560QuzA0JfB0Cfg,
    IwxCfgMaA0FmA0,
    IwxCfgMaB0Gf4A0,
    IwxCfgMaB0GfA0,
    IwxCfgMaB0HrB0,
    IwxCfgQuzA0HrB0,
    IwxCfgSoA0HrB0,
    IwxQuB0Hr1B0,
    IwxQuB0HrB0,
    IwxQuC0Hr1B0,
    IwxQuC0HrB0,
    IwxQuzA0Hr1B0,
}

impl DeviceConfig {
    // upstream: if_iwxvar.h iwx_2ax_cfg_so()
    pub const fn firmware(self) -> FirmwareConfig {
        match self {
            Self::SoGf4Ax411 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-so-a0-gf4-a0-89.ucode",
                pnvm: Some("/lib/firmware/iwlwifi-so-a0-gf4-a0.pnvm"),
                tx_with_siso_diversity: false,
                uhb_supported: true,
                xtal_latency: 12000,
                low_latency_xtal: true,
            },
            Self::Iwx2axCfgSoGf4A0Long => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-so-a0-gf4-a0-89.ucode",
                pnvm: Some("/lib/firmware/iwlwifi-so-a0-gf4-a0.pnvm"),
                tx_with_siso_diversity: false,
                uhb_supported: true,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::SoGfAx211 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-so-a0-gf-a0-89.ucode",
                pnvm: Some("/lib/firmware/iwlwifi-so-a0-gf-a0.pnvm"),
                tx_with_siso_diversity: false,
                uhb_supported: true,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::Iwx2axCfgSoGfA0Long => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-so-a0-gf-a0-89.ucode",
                pnvm: Some("/lib/firmware/iwlwifi-so-a0-gf-a0.pnvm"),
                tx_with_siso_diversity: false,
                uhb_supported: true,
                xtal_latency: 12000,
                low_latency_xtal: true,
            },
            Self::Iwx2axCfgSoJfB0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-so-a0-jf-b0-77.ucode",
                pnvm: None,
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::Iwx2axCfgTyGfA0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-ty-a0-gf-a0-89.ucode",
                pnvm: Some("/lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm"),
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::Iwx9560QuC0JfB0Cfg => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-Qu-c0-jf-b0-77.ucode",
                pnvm: None,
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::Iwx9560QuzA0JfB0Cfg => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-QuZ-a0-jf-b0-77.ucode",
                pnvm: None,
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxCfgMaA0FmA0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-ma-a0-fm-a0-89.ucode",
                pnvm: Some("/lib/firmware/iwlwifi-ma-a0-fm-a0.pnvm"),
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxCfgMaB0Gf4A0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-ma-b0-gf4-a0-89.ucode",
                pnvm: Some("/lib/firmware/iwlwifi-ma-b0-gf4-a0.pnvm"),
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxCfgMaB0GfA0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-ma-b0-gf-a0-89.ucode",
                pnvm: Some("/lib/firmware/iwlwifi-ma-b0-gf-a0.pnvm"),
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxCfgMaB0HrB0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-ma-b0-hr-b0-89.ucode",
                pnvm: None,
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxCfgQuzA0HrB0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-QuZ-a0-hr-b0-77.ucode",
                pnvm: None,
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxCfgSoA0HrB0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-so-a0-hr-b0-89.ucode",
                pnvm: None,
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxQuB0Hr1B0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-Qu-b0-hr-b0-77.ucode",
                pnvm: None,
                tx_with_siso_diversity: true,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxQuB0HrB0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-Qu-b0-hr-b0-77.ucode",
                pnvm: None,
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxQuC0Hr1B0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-Qu-c0-hr-b0-77.ucode",
                pnvm: None,
                tx_with_siso_diversity: true,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxQuC0HrB0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-Qu-c0-hr-b0-77.ucode",
                pnvm: None,
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
            Self::IwxQuzA0Hr1B0 => FirmwareConfig {
                firmware: "/lib/firmware/iwlwifi-QuZ-a0-hr-b0-77.ucode",
                pnvm: None,
                tx_with_siso_diversity: false,
                uhb_supported: false,
                xtal_latency: 0,
                low_latency_xtal: false,
            },
        }
    }
}

/// Runtime facts used by the table's matching predicates.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuntimeConfig {
    pub device: u16,
    pub subdevice: u16,
    pub mac_type: u16,
    pub mac_step: u8,
    pub rf_type: u16,
    pub rf_id: u8,
    pub no_160: u8,
    pub cores: u8,
    pub cdb: u8,
    pub jacket: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttachProfileError {
    UnknownProduct(u16),
    UnsupportedRevision,
    MissingRuntimeConfig,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AttachProfile {
    pub config: DeviceConfig,
    pub firmware: FirmwareConfig,
    pub family: crate::DeviceFamily,
    pub integrated: bool,
    pub ltr_delay: u8,
    pub low_latency_xtal: bool,
    pub xtal_latency: u32,
    pub tx_with_siso_diversity: bool,
    pub uhb_supported: bool,
    pub imr_enabled: bool,
    pub mac_addr_from_csr: u32,
    pub umac_prph_offset: u32,
    pub max_tfd_queue_size: usize,
}

/// Initialize per-product hardware defaults, then apply the reverse-row runtime config override.
// upstream: if_iwx.c iwx_find_device_cfg()
pub fn attach_profile(runtime: RuntimeConfig) -> Result<AttachProfile, AttachProfileError> {
    let (family, integrated, ltr_delay, low_latency, latency, imr) = match runtime.device {
        0x2723 => (crate::DeviceFamily::Family22000, false, 0, false, 0, false),
        0x02f0 | 0x06f0 if runtime.mac_type != 0x354 => {
            return Err(AttachProfileError::UnsupportedRevision);
        }
        0x02f0 | 0x06f0 => (crate::DeviceFamily::Family22000, true, 1, false, 500, false),
        0xa0f0 => (crate::DeviceFamily::Family22000, true, 1, false, 500, false),
        0x34f0 | 0x3df0 | 0x4df0 => (
            crate::DeviceFamily::Family22000,
            true,
            3,
            false,
            1820,
            false,
        ),
        0x43f0 => (
            crate::DeviceFamily::Family22000,
            true,
            2,
            true,
            12000,
            false,
        ),
        0x2725 | 0x2726 | 0x51f0 | 0x51f1 | 0x7e40 | 0x54f0 => {
            (crate::DeviceFamily::Ax210, false, 0, false, 0, false)
        }
        0x7a70 | 0x7f70 => (crate::DeviceFamily::Ax210, true, 2, true, 12000, true),
        0x7af0 => (crate::DeviceFamily::Ax210, true, 0, false, 0, false),
        0x7740 => (crate::DeviceFamily::Bz, true, 2, true, 12000, false),
        other => return Err(AttachProfileError::UnknownProduct(other)),
    };
    let config = lookup_config(runtime).ok_or(AttachProfileError::MissingRuntimeConfig)?;
    let firmware = config.firmware();
    let mut profile = AttachProfile {
        config,
        firmware,
        family,
        integrated,
        ltr_delay,
        low_latency_xtal: low_latency,
        xtal_latency: latency,
        tx_with_siso_diversity: false,
        uhb_supported: firmware.uhb_supported,
        imr_enabled: imr,
        mac_addr_from_csr: if family >= crate::DeviceFamily::Bz {
            0x30
        } else {
            0x380
        },
        umac_prph_offset: if family >= crate::DeviceFamily::Ax210 {
            0x300000
        } else {
            0
        },
        max_tfd_queue_size: if family >= crate::DeviceFamily::Ax210 {
            crate::rings::GEN3_MAX_TFD_QUEUE_SIZE
        } else {
            crate::rings::TX_RING_COUNT
        },
    };
    profile.tx_with_siso_diversity = firmware.tx_with_siso_diversity;
    profile.uhb_supported = firmware.uhb_supported;
    if firmware.xtal_latency != 0 {
        profile.xtal_latency = firmware.xtal_latency;
        profile.low_latency_xtal = firmware.low_latency_xtal;
    }
    Ok(profile)
}

impl RuntimeConfig {
    /// Derive subsystem fields and silicon facts exactly as `iwx_find_device_cfg()` does.
    // upstream: if_iwx.c iwx_find_device_cfg()
    pub const fn from_hardware(
        device: u16,
        subdevice: u16,
        mac_type: u16,
        mac_step: u8,
        rf_type: u16,
        cdb: u8,
        jacket: u8,
    ) -> Self {
        Self {
            device,
            subdevice,
            mac_type,
            mac_step,
            rf_type,
            rf_id: ((subdevice & 0x00f0) >> 4) as u8,
            no_160: ((subdevice & 0x0200) >> 9) as u8,
            cores: ((subdevice & 0x1c00) >> 10) as u8,
            cdb,
            jacket,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct DeviceInfo {
    device: Option<u16>,
    subdevice: Option<u16>,
    mac_type: Option<u16>,
    mac_step: Option<u8>,
    rf_type: Option<u16>,
    rf_id: Option<u8>,
    no_160: Option<u8>,
    cores: Option<u8>,
    cdb: Option<u8>,
    jacket: Option<u8>,
    config: DeviceConfig,
}

impl DeviceInfo {
    const fn matches(self, r: RuntimeConfig) -> bool {
        (self.device.is_none() || self.device.unwrap() == r.device)
            && (self.subdevice.is_none() || self.subdevice.unwrap() == r.subdevice)
            && (self.mac_type.is_none() || self.mac_type.unwrap() == r.mac_type)
            && (self.mac_step.is_none() || self.mac_step.unwrap() == r.mac_step)
            && (self.rf_type.is_none() || self.rf_type.unwrap() == r.rf_type)
            && (self.rf_id.is_none() || self.rf_id.unwrap() == r.rf_id)
            && (self.no_160.is_none() || self.no_160.unwrap() == r.no_160)
            && (self.cores.is_none() || self.cores.unwrap() == r.cores)
            && (self.cdb.is_none() || self.cdb.unwrap() == r.cdb)
            && (self.jacket.is_none() || self.jacket.unwrap() == r.jacket)
    }
}

// Keep exact source order; `lookup_config` walks this table in reverse.
const DEVICE_INFO_TABLE: [DeviceInfo; 97] = [
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(144),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(32),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(8224),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(36),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(784),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(1296),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(2576),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(57376),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(57380),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(16416),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(24608),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(24612),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(5747),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(10021),
        subdevice: Some(5748),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgTyGfA0,
    },
    DeviceInfo {
        device: Some(20976),
        subdevice: Some(5777),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(20976),
        subdevice: Some(5778),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(20977),
        subdevice: Some(5777),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(20977),
        subdevice: Some(5778),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(21744),
        subdevice: Some(5777),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(21744),
        subdevice: Some(5778),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(31344),
        subdevice: Some(144),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoGfA0Long,
    },
    DeviceInfo {
        device: Some(31344),
        subdevice: Some(152),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoGfA0Long,
    },
    DeviceInfo {
        device: Some(31344),
        subdevice: Some(176),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoGf4A0Long,
    },
    DeviceInfo {
        device: Some(31344),
        subdevice: Some(784),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoGfA0Long,
    },
    DeviceInfo {
        device: Some(31344),
        subdevice: Some(1296),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoGfA0Long,
    },
    DeviceInfo {
        device: Some(31344),
        subdevice: Some(2576),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoGfA0Long,
    },
    DeviceInfo {
        device: Some(31472),
        subdevice: Some(144),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(31472),
        subdevice: Some(152),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(31472),
        subdevice: Some(176),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(31344),
        subdevice: Some(5777),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(31344),
        subdevice: Some(5778),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(31472),
        subdevice: Some(784),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(31472),
        subdevice: Some(1296),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(31472),
        subdevice: Some(2576),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(32624),
        subdevice: Some(5777),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(32624),
        subdevice: Some(5778),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: Some(10022),
        subdevice: Some(5745),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(10022),
        subdevice: Some(5746),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(20976),
        subdevice: Some(5745),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(20976),
        subdevice: Some(5746),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(21744),
        subdevice: Some(5745),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(21744),
        subdevice: Some(5746),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(31344),
        subdevice: Some(5745),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(31344),
        subdevice: Some(5746),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(31472),
        subdevice: Some(5745),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(31472),
        subdevice: Some(5746),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(32624),
        subdevice: Some(5745),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(32624),
        subdevice: Some(5746),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: Some(32320),
        subdevice: Some(5745),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::IwxCfgMaB0GfA0,
    },
    DeviceInfo {
        device: Some(32320),
        subdevice: Some(5746),
        mac_type: None,
        mac_step: None,
        rf_type: None,
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: None,
        jacket: None,
        config: DeviceConfig::IwxCfgMaB0GfA0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(264),
        rf_id: Some(6),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuC0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(264),
        rf_id: Some(6),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuC0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(264),
        rf_id: Some(10),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuC0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(264),
        rf_id: Some(10),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuC0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuC0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuC0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: Some(5457),
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuC0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: Some(5458),
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuC0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(53),
        mac_step: None,
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuzA0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(53),
        mac_step: None,
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuzA0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(53),
        mac_step: None,
        rf_type: Some(264),
        rf_id: Some(10),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuzA0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(53),
        mac_step: None,
        rf_type: Some(264),
        rf_id: Some(10),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuzA0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: Some(5457),
        mac_type: Some(53),
        mac_step: None,
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuzA0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: Some(5458),
        mac_type: Some(53),
        mac_step: None,
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx9560QuzA0JfB0Cfg,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(1),
        rf_type: Some(268),
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxQuB0Hr1B0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(1),
        rf_type: Some(266),
        rf_id: None,
        no_160: Some(1),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxQuB0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(268),
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxQuC0Hr1B0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(266),
        rf_id: None,
        no_160: Some(1),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxQuC0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(51),
        mac_step: Some(2),
        rf_type: Some(266),
        rf_id: None,
        no_160: Some(0),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxQuC0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(53),
        mac_step: None,
        rf_type: Some(268),
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxQuzA0Hr1B0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(53),
        mac_step: Some(1),
        rf_type: Some(266),
        rf_id: None,
        no_160: Some(1),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxCfgQuzA0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(264),
        rf_id: Some(6),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(264),
        rf_id: Some(10),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(264),
        rf_id: Some(6),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(264),
        rf_id: Some(10),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(266),
        rf_id: None,
        no_160: Some(1),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxCfgSoA0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(268),
        rf_id: None,
        no_160: Some(1),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxCfgSoA0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(266),
        rf_id: None,
        no_160: Some(0),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxCfgSoA0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(266),
        rf_id: None,
        no_160: Some(1),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxCfgSoA0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(268),
        rf_id: None,
        no_160: Some(1),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxCfgSoA0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(266),
        rf_id: None,
        no_160: Some(0),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxCfgSoA0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(269),
        rf_id: None,
        no_160: Some(0),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(67),
        mac_step: None,
        rf_type: Some(269),
        rf_id: None,
        no_160: Some(0),
        cores: None,
        cdb: Some(1),
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(269),
        rf_id: None,
        no_160: Some(0),
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::SoGfAx211,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(269),
        rf_id: None,
        no_160: Some(0),
        cores: None,
        cdb: Some(1),
        jacket: None,
        config: DeviceConfig::SoGf4Ax411,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(261),
        rf_id: Some(3),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(264),
        rf_id: Some(6),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(264),
        rf_id: Some(10),
        no_160: Some(0),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(264),
        rf_id: Some(6),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(55),
        mac_step: None,
        rf_type: Some(264),
        rf_id: Some(10),
        no_160: Some(1),
        cores: Some(0),
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::Iwx2axCfgSoJfB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(68),
        mac_step: None,
        rf_type: Some(266),
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxCfgMaB0HrB0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(68),
        mac_step: None,
        rf_type: Some(269),
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxCfgMaB0GfA0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(68),
        mac_step: None,
        rf_type: Some(269),
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: Some(1),
        jacket: None,
        config: DeviceConfig::IwxCfgMaB0Gf4A0,
    },
    DeviceInfo {
        device: None,
        subdevice: None,
        mac_type: Some(68),
        mac_step: None,
        rf_type: Some(274),
        rf_id: None,
        no_160: None,
        cores: None,
        cdb: Some(0),
        jacket: None,
        config: DeviceConfig::IwxCfgMaA0FmA0,
    },
];

/// Match the complete OpenBSD iwx runtime table, from last entry to first.
// upstream: if_iwx.c iwx_find_device_cfg()
pub fn lookup_config(runtime: RuntimeConfig) -> Option<DeviceConfig> {
    for info in DEVICE_INFO_TABLE.iter().rev() {
        if info.matches(runtime) {
            return Some(info.config);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    const AX211: RuntimeConfig = RuntimeConfig::from_hardware(0x54f0, 0x4070, 0x43, 0, 0x10d, 0, 0);
    #[test]
    fn full_source_table_is_kept_in_order() {
        assert_eq!(DEVICE_INFO_TABLE.len(), 97);
    }
    #[test]
    fn matches_full_openbsd_pci_attach_list() {
        assert!(matches_pci_device(INTEL_VENDOR_ID, AX211_DEVICE_ID));
        assert!(matches_pci_device(INTEL_VENDOR_ID, 0x2723));
        assert!(!matches_pci_device(0xffff, 0x54f0));
        assert!(!matches_pci_device(INTEL_VENDOR_ID, 0xffff));
    }
    #[test]
    fn ax211_runtime_selects_so_gf_and_linux_firmware_api89() {
        assert_eq!(lookup_config(AX211), Some(DeviceConfig::SoGfAx211));
        let fw = DeviceConfig::SoGfAx211.firmware();
        assert_eq!(fw.firmware, "/lib/firmware/iwlwifi-so-a0-gf-a0-89.ucode");
        assert_eq!(fw.pnvm, Some("/lib/firmware/iwlwifi-so-a0-gf-a0.pnvm"));
        assert!(fw.uhb_supported);
    }
    #[test]
    fn attach_profile_combines_product_defaults_with_runtime_firmware_config() {
        let profile = attach_profile(AX211).unwrap();
        assert_eq!(profile.config, DeviceConfig::SoGfAx211);
        assert_eq!(profile.family, crate::DeviceFamily::Ax210);
        assert!(!profile.integrated);
        assert_eq!(profile.mac_addr_from_csr, 0x380);
        assert_eq!(profile.umac_prph_offset, 0x300000);
        assert_eq!(profile.max_tfd_queue_size, crate::GEN3_MAX_TFD_QUEUE_SIZE);
        assert!(profile.uhb_supported);
        assert_eq!(
            profile.firmware.firmware,
            "/lib/firmware/iwlwifi-so-a0-gf-a0-89.ucode"
        );
        assert_eq!(
            attach_profile(RuntimeConfig::from_hardware(0xffff, 0, 0, 0, 0, 0, 0)),
            Err(AttachProfileError::UnknownProduct(0xffff))
        );
    }
    #[test]
    fn exact_killer_1691_1692_1671_1672_rows_win_in_reverse_order() {
        for sub in [0x1691, 0x1692] {
            assert_eq!(
                lookup_config(RuntimeConfig {
                    subdevice: sub,
                    cdb: 1,
                    ..AX211
                }),
                Some(DeviceConfig::SoGf4Ax411)
            );
        }
        for sub in [0x1671, 0x1672] {
            assert_eq!(
                lookup_config(RuntimeConfig {
                    subdevice: sub,
                    ..AX211
                }),
                Some(DeviceConfig::SoGfAx211)
            );
        }
    }
    #[test]
    fn distinct_so_and_sof_mac_types_both_match_their_source_rows() {
        let so = RuntimeConfig {
            mac_type: 0x37,
            ..AX211
        };
        assert_eq!(lookup_config(so), Some(DeviceConfig::SoGfAx211));
        assert_eq!(lookup_config(RuntimeConfig { no_160: 1, ..AX211 }), None);
        assert_eq!(
            lookup_config(RuntimeConfig {
                rf_type: 0,
                ..AX211
            }),
            None
        );
        assert_eq!(
            lookup_config(RuntimeConfig {
                mac_type: 0,
                ..AX211
            }),
            None
        );
    }
}
