[package]
name = "tk-axdriver-nvme"
version = "0.1.0"
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axdriver_block = { package = "tk-axdriver-block", path = "../tk-axdriver-block" }
tk-vtd = { path = "../tk-vtd" }

[package.metadata.thekernel]
layer = "platform"

[package.metadata.thekernel.host-test]
selected = true
